### ISSUE TITLE
How is the dropout implemented?

### ISSUE THREAD

**Issue by fangxiaoran** [Codersadis/Content-aware-CNN-loop-filter-for-HEVC#1]
Hi, I read your paper "_Content-Aware Convolutional Neural Network for In-Loop Filtering in High Efficiency Video Coding_" recently and got some questions.

The first one is, you said the dropout probability is 1. Does it mean the keep probability is 1, or the drop probability is 1. Both look strange.

Another one is, for the first "connection unit" in the network, the input x and output y have different feature map numbers (x is [?, 38, 38, 1] and y is [?, 38, 38, 64], is that right?). How dose the dropout connection change the feature map number of x, so that the output of dropout connection is consistent with the output of convolution layer dimension?

Thanks and looking forward to your reply.

**Comment by Codersadis** [comment]
hi, as descriped in our paper, we dropout all the connections so that the dimensions could be consistent.

**Comment by Codersadis** [comment]
> Hi, I read your paper "_Content-Aware Convolutional Neural Network for In-Loop Filtering in High Efficiency Video Coding_" recently and got some questions.
> 
> The first one is, you said the dropout probability is 1. Does it mean the keep probability is 1, or the drop probability is 1. Both look strange.
> 
> Another one is, for the first "connection unit" in the network, the input x and output y have different feature map numbers (x is [?, 38, 38, 1] and y is [?, 38, 38, 64], is that right?). How dose the dropout connection change the feature map number of x, so that the output of dropout connection is consistent with the output of convolution layer dimension?
> 
> Thanks and looking forward to your reply.

hi, as descriped in our paper, we dropout all the connections so that the dimensions could be consistent.

**Comment by Codersadis** [comment]
> Hi, I read your paper "_Content-Aware Convolutional Neural Network for In-Loop Filtering in High Efficiency Video Coding_" recently and got some questions.
> 
> The first one is, you said the dropout probability is 1. Does it mean the keep probability is 1, or the drop probability is 1. Both look strange.
> 
> Another one is, for the first "connection unit" in the network, the input x and output y have different feature map numbers (x is [?, 38, 38, 1] and y is [?, 38, 38, 64], is that right?). How dose the dropout connection change the feature map number of x, so that the output of dropout connection is consistent with the output of convolution layer dimension?
> 
> Thanks and looking forward to your reply.

hi, as descriped in our paper, we set the dropout all the connections in the dropout branch so that the dimensions could be consistent.
