### ISSUE TITLE
How do you get HEVC compressed data?

### ISSUE THREAD

**Issue by fredlll** [Codersadis/Content-aware-CNN-loop-filter-for-HEVC#3]
How did you generate the HEVC compressed data? e.g. qp22.

How do you extract the images in loop? Can you share the code?

Thx

**Comment by Codersadis** [comment]
> How did you generate the HEVC compressed data? e.g. qp22.
> 
> How do you extract the images in loop? Can you share the code?
> 
> Thx

We use HEVC codec to compress the pristine image using qp22 and then construct the training samples. Refer to [here](https://github.com/Codersadis/Content-aware-CNN-loop-filter-for-HEVC/tree/master/Trainingdata) see the code for training data and h5 file generation.

Regarding the code for codec with deep learning, plz see [this](https://github.com/FVC2018/DLVC).
